# Site settings
title:        M. Mucahid Benlioglu
email:        m.mucahidbenlioglu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

linkedin_username:  mbenlioglu
github_username:    mbenlioglu

# Build settings
markdown: kramdown
